registration:
  channel_name: "ğŸ“‹-registrar-se"
  force_on_join: true
  nickname_prefix: ""   # <-- vazio
  unregistered_role_name: "â›” NÃ£o Registrado"
  registered_role_name: "âœ… Registrado"
  ping_on_join_in_channel: false
  audit_interval_min: 10